### ISSUE TITLE
Support protobuf messages in Unity

### ISSUE THREAD

**Issue by oliverlee** [oliverlee/phobos#115]
- [x] open serial port
- [x] read from serial port
- [x] cobs decode messages
- [x] protobuf decode cobs decoded messages
- [x] replace old implementation

> This should probably be an issue in https://github.com/oliverlee/bikesim but it's easier to track all the things in one place.

**Comment by mickvangelderen** [comment]
- [ ] port c++ cobs to c#

**Comment by mickvangelderen** [comment]
Code from the old project has been used to create a new project: https://gitlab.com/bikelab/phobos-visualiser
