### ISSUE TITLE
Configure cmake so that only changed files are rebuilt

### ISSUE THREAD

**Issue by mickvangelderen** [oliverlee/phobos#132]
It seems like more than needed is rebuilt.

**Comment by oliverlee** [comment]
Not sure if you're referring to the chibios binaries but if you are, each translation unit gets compiled PER binary. This is because each binary defines its own set of configuration files which in turn result in the ch and hal libraries getting conditionally compiled.

**Comment by mickvangelderen** [comment]
Never mind, things are working as they should after all. Not sure why I thought they weren't.
