### ISSUE TITLE
Fix ADC events

### ISSUE THREAD

**Issue by oliverlee** [oliverlee/phobos#148]
The ADC events are never broadcast.

**Comment by mickvangelderen** [comment]
What are ADC events?

**Comment by oliverlee** [comment]
ADC is the analog to digital converter. The Analog class is supposed to broadcast two events: `adc_eventflag_complete` and `adc_eventflag_error`. The events are defined here: https://github.com/oliverlee/phobos/blob/f2c686b29f62306f04b3828090c80b70a71f1ddf/src/analog.cc#L29-L30

An example using events is here: https://github.com/oliverlee/phobos/blob/f2c686b29f62306f04b3828090c80b70a71f1ddf/demos/adc/main.cc

**Comment by oliverlee** [comment]
This should probably be fixed for the steer-by-wire bike I think as this bug isn't causing problems for the static simulator at the moment.

**Comment by oliverlee** [comment]
This doesn't appear to be necessary at the moment.
