### ISSUE TITLE
Add tool description to README

### ISSUE THREAD

**Issue by oliverlee** [oliverlee/phobos#163]
There are short descriptions of demos and projects. We should also have short descriptions of tools.

**Comment by mickvangelderen** [comment]
What if we put a README in each project/demo/tool folders?

- :+1: Documentation close to code
- :+1: Easier to discover the repository
- :+1: Less clutter in main README
- :-1: More files to keep updated
- :-1: Common text is not easily shared

**Comment by oliverlee** [comment]
I like that idea.
