### ISSUE TITLE
Add option to toggle roll in visualization

### ISSUE THREAD

**Issue by mickvangelderen** [oliverlee/phobos#166]
Oliver thought disabling roll for occulus works on the monitor but not for the occulus.

**Comment by oliverlee** [comment]
This should also be added to phobos-visualizer.

**Comment by oliverlee** [comment]
This needs to be implemented for standard monitor and oculus.

**Comment by mickvangelderen** [comment]
Roll of the entire camera mount is always disabled now. The camera mount object is following the bicycle object. Need to add a swivel object that keeps the camera flat while still having it move with the roll of the bike. 
![bicycle mount](https://user-images.githubusercontent.com/5444990/27476285-6fb090a6-5808-11e7-836a-4d90da66c9eb.jpg)

**Comment by mickvangelderen** [comment]
Toggling roll was implemented. Improvement issue: #229
