### ISSUE TITLE
Save microcontroller messages to file

### ISSUE THREAD

**Issue by mickvangelderen** [oliverlee/phobos#172]
The /dev/ttyACM0 (or another file) stream is consumed by Unity. To replay a visualisation we need it logged to a file.

**Comment by oliverlee** [comment]
We should use __.pbf__ for the file extension of the log files to denote that it is framed protobuf data.

**Comment by mickvangelderen** [comment]
Fixed by https://gitlab.com/bikelab/phobos-visualizer/commit/58163f981099739dc857805e9ba11375d193a3f0
