### ISSUE TITLE
Improve visuals

### ISSUE THREAD

**Issue by oliverlee** [oliverlee/phobos#174]
This needs to be better. I guess we should add some trees and a road.

**Comment by mickvangelderen** [comment]
@oliverlee Any particular path for the road?

**Comment by oliverlee** [comment]
If you have time to work on this, ask Arend. I'm not sure what he wants as I think whatever is implemented is already sufficient.

**Comment by oliverlee** [comment]
The general topology should look like a 3x3 grid:

    +---------+---------+------------+
    |         |         |            |
    |         |         |            |
    +---------+---------+------------+
    |         |         |            |
    |         |         |            |
    |         |         |            |
    +---------+---------+------------+
    |         |         |            |
    |         |         |            |
    |         |         |            |
    |         |         |            |
    +---------+---------+------------+
- The grid should _not_ be evenly spaced.
- The perimeter of the grid should be 1 km.
- The corners of the grid should be curved (radius of curvature is not strictly defined right now)
- The road should be composed of a two lane bike path: https://en.wikipedia.org/wiki/File:Bicycle_lane_Dronten.JPG

Trees can be populated throughout so that it "looks good". Ground that is not road can be grass or a grass texture.

**Comment by oliverlee** [comment]
Maybe we could take a look at this as well: https://github.com/fcl-engaging-mobility/UnityScripts

**Comment by mickvangelderen** [comment]
![image](https://user-images.githubusercontent.com/5444990/27490553-fd04f696-583e-11e7-809c-db4b4b226dd2.png)
First iteration

**Comment by oliverlee** [comment]
Implemented here: https://gitlab.com/bikelab/phobos-visualizer/commit/4c315acc6d99940e6e612ee1f0f77ca1739562b8
