### ISSUE TITLE
Display fps on screen

### ISSUE THREAD

**Issue by oliverlee** [oliverlee/phobos#175]
Why not? People will ask about this (as well as the time it takes to transmit a message and draw it to screen but that's a bit trickier to calculate).

**Comment by mickvangelderen** [comment]
Interesting frequencies include:

- Drawing frequency (Update)
- Update frequency (Fixed Update)
- Received message frequency

**Comment by oliverlee** [comment]
Is anything done (or will ever be done) in fixed update?

Definitely update, after all this gives us fps.
Possibly received message frequency, but maybe as X messages/second as we would be receiving simulation state messages at 1 kHz and pose messages at 120 Hz.

**Comment by mickvangelderen** [comment]
We should read from the serial port in fixed update. Getting all the messages is critical for logging. If we read from serial in update and the frame rate drops, flimnap will be dropping messages.

**Comment by oliverlee** [comment]
I figured a low priority background thread would be continuously reading from the serial port, not necessarily at any fixed rate.

**Comment by mickvangelderen** [comment]
That makes more sense, yes.
