### ISSUE TITLE
Create phobos-visualizer build script

### ISSUE THREAD

**Issue by mickvangelderen** [oliverlee/phobos#184]
We need a script that builds binaries for OS X, Windows and Linux using Unity and compresses the applications so we can attach them to phobos releases. 

#171

**Comment by oliverlee** [comment]
Looks like setting up a unity build is easy enough:
http://blog.stablekernel.com/continuous-integration-for-unity-5-using-travisci
https://jonathan.porta.codes/2015/04/17/automatically-build-your-unity3d-project-in-the-cloud-using-travisci-for-free/

I don't know anything about copying the built binaries to somewhere. Would we create a nightly release and attach the binaries to that? Do you have experience with that?

**Comment by mickvangelderen** [comment]
Thought about it, never written a working solution though.

**Comment by oliverlee** [comment]
Looks like the Github allows something for releases (not branches): https://docs.travis-ci.com/user/deployment/releases/

**Comment by mickvangelderen** [comment]
Uploading attachments to releases on gitlab: https://gitlab.com/gitlab-org/gitlab-ce/issues/18486

Example scripts: http://answers.unity3d.com/questions/9382/build-from-script.html

**Comment by mickvangelderen** [comment]
Been working on this but it is very hard to activate a unity install from the command line. Activation is required for any command including building. The reason for this is probably that Unity has their own "Cloud building" solution. 

Putting more time into this is not worth it. A build script is still useful.

**Comment by mickvangelderen** [comment]
Fixed by https://gitlab.com/bikelab/phobos-visualizer/commit/92a93d971a8c54fea6225ce8f7c425389c4d17e2

**Comment by mickvangelderen** [comment]
Updated release v0.2 with win|lin|mac 32|64 builds.
