### ISSUE TITLE
Determine storage format

### ISSUE THREAD

**Issue by oliverlee** [oliverlee/phobos#186]
So far, I assume logs will be the COBS framed serialized protobuf data. I'm not sure this is the best approach storing the data, as we'll need to do a bunch of processing to actually look at it with other tools. And this will be a problem if anyone else besides us (@oliverlee, @mickvangelderen) is working with the data at a later date, particularly since it encapsulates the framing protocol and requires the protobuf schema.

It seems like hdf5 seems to be a hip format to store stuff. We could write a tool that transforms the data from framed serialized protobuf to hfd5 (and possibly do this directly in Unity).

I imagine we need a post-processing tool as the steer-by-wire project would save the framed serialized protobuf disk to minimize resources used when logging.

**Comment by oliverlee** [comment]
As replay requires a protobuf stream, I don't think we should do this in Unity.

Issue https://github.com/oliverlee/phobos/issues/172 relates to actually logging in Unity.

**Comment by oliverlee** [comment]
This was an interesting read: http://cyrille.rossant.net/should-you-use-hdf5/

**Comment by mickvangelderen** [comment]
I don't know about any well known binary arbitrary data file formats. We can support multiple formats once we have the conversion tools easily so experiment away :smile:.

**Comment by oliverlee** [comment]
We will have two types of files:
- logging format: framed serialized protobuf, file extension of __.pbf__
- storage format: hdf5, file extension of __.h5__

**Comment by mickvangelderen** [comment]
> logging format: framed serialized protobuf, file extension of .pbf

I'd like to see `.pb.cobs`, similar to `.tar.gz`.

**Comment by oliverlee** [comment]
We need to go through the repo and rename files to __.pb.cobs__

**Comment by oliverlee** [comment]
What we have works for now so maybe we'll reopen this if necessary.
