### ISSUE TITLE
wheel angle in viz too large

### ISSUE THREAD

**Issue by oliverlee** [oliverlee/phobos#193]
Wheel value grows too large as isn't getting normalized at all.

**Comment by mickvangelderen** [comment]
How is velocity better? In general, you can estimate the velocity from a few position samples but you need all velocity samples to find the position.

**Comment by mickvangelderen** [comment]
I'm curious what happened that brought up this issue.

**Comment by oliverlee** [comment]
The angular position of the rear wheel doesn't really mean much and is hard to make sense of it when shown on screen as a number, although it does help in rendering the wheels.

Displaying the forward velocity of the bicycle would be better as this a common metric people use when riding.

The value is shown on screen and grows away from zero when pedaling.

**Comment by mickvangelderen** [comment]
Ah you are talking about the status panel. I see what you mean now.
