### ISSUE TITLE
Select option auto detected port

### ISSUE THREAD

**Issue by mickvangelderen** [oliverlee/phobos#206]
![image](https://user-images.githubusercontent.com/5444990/27338290-0f2a676e-55d5-11e7-81e2-dd94f59bb879.png)
A port was detected but the option was not selected properly.

**Comment by oliverlee** [comment]
Don't work on this before the demo unless it is a quick fix.

**Comment by mickvangelderen** [comment]
Is a quick fix.

**Comment by mickvangelderen** [comment]
Need to test https://gitlab.com/bikelab/phobos-visualizer/commit/0cadf3716d0d13a44ac43fd105cea1df24622e47

**Comment by mickvangelderen** [comment]
Works
