### ISSUE TITLE
Motor jerkiness

### ISSUE THREAD

**Issue by oliverlee** [oliverlee/phobos#222]
See here:
![screen shot 2017-06-22 at 14 24 09](https://user-images.githubusercontent.com/2965031/27433854-ad0bc8ec-5756-11e7-8235-88bb4e21da24.png)
![screen shot 2017-06-22 at 14 25 23](https://user-images.githubusercontent.com/2965031/27433853-ad08d826-5756-11e7-9c69-9db5b83799b9.png)

Data is from here:  https://github.com/oliverlee/phobos/pull/198#issuecomment-310365293

**Comment by oliverlee** [comment]
This is fixed by setting the analog input low pass filter to 100 Hz in the kollmorgen workbench.

**Comment by mickvangelderen** [comment]
I have some questions to improve my understanding of the system:

1. Is the commanded steer velocity limited to +-100 deg/s?
2. Is it coincidence that the low pass filter is set to Hz and the velocity limit is 100 deg/s?
3. How did you determine 100 Hz is a good maximum frequency?

**Comment by oliverlee** [comment]
> Is the commanded steer velocity limited to +-100 deg/s?

Yes this is set in the motor drive configuration. The drive accepts a velocity input from ±12V. We map this to ±100 deg/s.

> Is it coincidence that the low pass filter is set to Hz and the velocity limit is 100 deg/s?

Yes. The low pass filter cutoff frequency is not related to the velocity limit.

> How did you determine 100 Hz is a good maximum frequency?
Intuition. We don't expect the bicycle dynamics to be that high. The cutoff frequency was reduced to 100 Hz from 500 Hz.
