### ISSUE TITLE
Create release v0.2

### ISSUE THREAD

**Issue by oliverlee** [oliverlee/phobos#227]
Tag release v0.2 for July demo. The latest possible due date Friday 30 June.

We will need to build binaries of the Unity environment and attach them to this release.

**Comment by oliverlee** [comment]
@mickvangelderen We need some cool codenames for the version numbers. This would one would have the start with a 'B' and we could name the v0.1 as well.

What about these? https://en.wikipedia.org/wiki/Category:Middle-earth_cities_and_towns

**Comment by oliverlee** [comment]
or https://en.wikipedia.org/wiki/Mars_(mythology) or https://en.wikipedia.org/wiki/List_of_films_set_on_Mars

**Comment by mickvangelderen** [comment]
Please no

**Comment by oliverlee** [comment]
Resolved: https://github.com/oliverlee/phobos/releases/tag/v0.2
