### ISSUE TITLE
Give rider roll angle feedback

### ISSUE THREAD

**Issue by mickvangelderen** [oliverlee/phobos#229]
Roll of the entire camera mount is always disabled now. The camera mount object is following the bicycle object. 

One idea is to add a swivel object that keeps the camera flat while still having it move with the roll of the bike. 
![bicycle mount](https://user-images.githubusercontent.com/5444990/27476285-6fb090a6-5808-11e7-836a-4d90da66c9eb.jpg)

Another possibility is a HUD element indicating roll.

**Comment by mickvangelderen** [comment]
Other suggestions:

- Have the sky box *not* rotate with the world.
- Scale the roll rate down emperically.
- View the player actor (bicycle) in third person, even though that might cause other mismatches.

**Comment by oliverlee** [comment]
I think we want to implement all 3, but not necessarily by Friday.

**Comment by mickvangelderen** [comment]
Apart from the skybox everything is implemented and seems sufficient to provide feedback https://github.com/oliverlee/phobos/issues/233.
