### ISSUE TITLE
Fix replaying

### ISSUE THREAD

**Issue by mickvangelderen** [oliverlee/phobos#241]
Either the .pb.cobs files are incorrectly written or the replay scene doesn't read them correctly.

**Comment by mickvangelderen** [comment]
Seems I must check https://github.com/oliverlee/phobos/issues/244 first.

**Comment by oliverlee** [comment]
This is dependent on #153

**Comment by mickvangelderen** [comment]
The log files were indeed corrupt. [This commit](https://gitlab.com/bikelab/phobos-visualizer/commit/c896d3739ff431cc6340961eedd0089356c809b4) fixed that problem.
