### ISSUE TITLE
Build errors with UnityEditor

### ISSUE THREAD

**Issue by oliverlee** [oliverlee/phobos#248]
The UnityEditor namespace is not available for builds.

**Comment by mickvangelderen** [comment]
http://answers.unity3d.com/questions/316805/unityeditor-namespace-not-found.html

**Comment by mickvangelderen** [comment]
Fixed by https://gitlab.com/bikelab/phobos-visualizer/commit/b8aa22ea22d4f9451b6fb91314f1ec5b65061179
