### ISSUE TITLE
Roll sliders do not work in builds

### ISSUE THREAD

**Issue by oliverlee** [oliverlee/phobos#254]

**Comment by mickvangelderen** [comment]
This probably has to do with https://github.com/oliverlee/phobos/issues/245. I guess the issue has to be reopened.

**Comment by mickvangelderen** [comment]
Correction: I'm not so sure anymore because I changed the CameraViewSwitcher script to not affect the rotation anymore. Also, I just built the project on Windows 10 and the mount and swivel roll sliders work for me.

**Comment by oliverlee** [comment]
I didn't notice them to have any effect when I used them today on the lab
machine.

**Comment by mickvangelderen** [comment]
@oliverlee What about today?

**Comment by oliverlee** [comment]
Tested and works with https://gitlab.com/bikelab/phobos-visualizer/commit/57ededdedb5d7d5e02f5c27863dddc1cb74526c2
