### ISSUE TITLE
Sort simulation messages

### ISSUE THREAD

**Issue by mickvangelderen** [oliverlee/phobos#270]
The .cobs.pb.gz file format allows simulation messages to be stored out of order. The visualization currently asserts that they are in order in debug builds. It would be better to simply sort the messages after loading them into memory. 

`ReplayScene.cs`

**Comment by oliverlee** [comment]
Is this a problem? It seems unlikely to happen.

**Comment by mickvangelderen** [comment]
Was no effort. Code is easier to understand. Replaying works in more cases. https://gitlab.com/bikelab/phobos-visualizer/commit/75c030dedc5ef6e0ccab5013497d9fba4a3ac59a
